INSERT INTO XSM_xdir_cat VALUES (154, 0, 'Art and Collectibles', 'http://');
INSERT INTO XSM_xdir_cat VALUES (155, 0, 'Automotive', 'http://');
INSERT INTO XSM_xdir_cat VALUES (156, 0, 'Community', 'http://');
INSERT INTO XSM_xdir_cat VALUES (157, 0, 'Computers and Internet', 'http://');
INSERT INTO XSM_xdir_cat VALUES (158, 0, 'Entertainment and Leisure', 'http://');
INSERT INTO XSM_xdir_cat VALUES (159, 0, 'Financial Services', 'http://');
INSERT INTO XSM_xdir_cat VALUES (160, 0, 'Food and Beverage', 'http://');
INSERT INTO XSM_xdir_cat VALUES (161, 0, 'Gifts and Flowers', 'http://');
INSERT INTO XSM_xdir_cat VALUES (162, 0, 'Health and Medicine', 'http://');
INSERT INTO XSM_xdir_cat VALUES (163, 0, 'Home and Garden', 'http://');
INSERT INTO XSM_xdir_cat VALUES (164, 0, 'Home Contractors', 'http://');
INSERT INTO XSM_xdir_cat VALUES (165, 0, 'Insurance', 'http://');
INSERT INTO XSM_xdir_cat VALUES (166, 0, 'Legal Services', 'http://');
INSERT INTO XSM_xdir_cat VALUES (167, 0, 'Personal Care', 'http://');
INSERT INTO XSM_xdir_cat VALUES (168, 0, 'Pets', 'http://');
INSERT INTO XSM_xdir_cat VALUES (169, 0, 'Professional Services', 'http://');
INSERT INTO XSM_xdir_cat VALUES (170, 0, 'Real Estate', 'http://');
INSERT INTO XSM_xdir_cat VALUES (171, 0, 'Restaurants', 'http://');
INSERT INTO XSM_xdir_cat VALUES (172, 0, 'Retail Shopping', 'http://');
INSERT INTO XSM_xdir_cat VALUES (173, 0, 'Sports and Recreation', 'http://');
INSERT INTO XSM_xdir_cat VALUES (174, 0, 'Travel and Transportation', 'http://');
INSERT INTO XSM_xdir_cat VALUES (175, 154, 'Antiques', '');
INSERT INTO XSM_xdir_cat VALUES (176, 154, 'Artists', '');
INSERT INTO XSM_xdir_cat VALUES (177, 154, 'Crafts and Hobbies', '');
INSERT INTO XSM_xdir_cat VALUES (178, 154, 'Fine Art', '');
INSERT INTO XSM_xdir_cat VALUES (179, 154, 'Fine Jewelry', '');
INSERT INTO XSM_xdir_cat VALUES (180, 154, 'Graphic Design', '');
INSERT INTO XSM_xdir_cat VALUES (181, 154, 'Picture Framing', '');
INSERT INTO XSM_xdir_cat VALUES (182, 155, 'Auto Detailing', '');
INSERT INTO XSM_xdir_cat VALUES (183, 155, 'Auto Parts', '');
INSERT INTO XSM_xdir_cat VALUES (184, 155, 'Body Repair and Paint', '');
INSERT INTO XSM_xdir_cat VALUES (185, 155, 'Brake Service', '');
INSERT INTO XSM_xdir_cat VALUES (186, 155, 'Car Audio', '');
INSERT INTO XSM_xdir_cat VALUES (187, 155, 'Car Dealers', '');
INSERT INTO XSM_xdir_cat VALUES (188, 155, 'Car Washes', '');
INSERT INTO XSM_xdir_cat VALUES (189, 155, 'Driving Schools', '');
INSERT INTO XSM_xdir_cat VALUES (190, 155, 'Exhaust and Emissions', '');
INSERT INTO XSM_xdir_cat VALUES (191, 155, 'Gas Stations', '');
INSERT INTO XSM_xdir_cat VALUES (192, 155, 'Glass', '');
INSERT INTO XSM_xdir_cat VALUES (193, 155, 'Motorcycle Dealers', '');
INSERT INTO XSM_xdir_cat VALUES (194, 155, 'Moving and Movers', '');
INSERT INTO XSM_xdir_cat VALUES (195, 155, 'Oil and Lube', '');
INSERT INTO XSM_xdir_cat VALUES (196, 155, 'Repair and Service', '');
INSERT INTO XSM_xdir_cat VALUES (197, 155, 'Towing', '');
INSERT INTO XSM_xdir_cat VALUES (198, 156, 'Cemeteries', '');
INSERT INTO XSM_xdir_cat VALUES (199, 156, 'Child Care', '');
INSERT INTO XSM_xdir_cat VALUES (200, 156, 'Clubs and Organizations', '');
INSERT INTO XSM_xdir_cat VALUES (201, 156, 'Education and Instruction', '');
INSERT INTO XSM_xdir_cat VALUES (202, 156, 'Fire and Emergency', '');
INSERT INTO XSM_xdir_cat VALUES (203, 156, 'Funeral Homes', '');
INSERT INTO XSM_xdir_cat VALUES (204, 156, 'Government', '');
INSERT INTO XSM_xdir_cat VALUES (205, 156, 'Law Enforcement', '');
INSERT INTO XSM_xdir_cat VALUES (206, 156, 'Libraries', '');
INSERT INTO XSM_xdir_cat VALUES (207, 156, 'Marriage Counseling', '');
INSERT INTO XSM_xdir_cat VALUES (208, 156, 'Media and Publications', '');
INSERT INTO XSM_xdir_cat VALUES (209, 156, 'Parks', '');
INSERT INTO XSM_xdir_cat VALUES (210, 156, 'Post Offices', '');
INSERT INTO XSM_xdir_cat VALUES (211, 156, 'Religion and Spirituality', '');
INSERT INTO XSM_xdir_cat VALUES (212, 156, 'Senior Services', '');
INSERT INTO XSM_xdir_cat VALUES (213, 156, 'Social and Welfare Services', '');
INSERT INTO XSM_xdir_cat VALUES (214, 156, 'Youth Groups', '');
INSERT INTO XSM_xdir_cat VALUES (215, 157, 'Classes and Instruction', '');
INSERT INTO XSM_xdir_cat VALUES (216, 157, 'Accessories and Services', '');
INSERT INTO XSM_xdir_cat VALUES (217, 157, 'Consultants', '');
INSERT INTO XSM_xdir_cat VALUES (218, 157, 'Computer Retailers', '');
INSERT INTO XSM_xdir_cat VALUES (219, 157, 'Internet Service Providers', '');
INSERT INTO XSM_xdir_cat VALUES (220, 157, 'Web Design', '');
INSERT INTO XSM_xdir_cat VALUES (221, 157, 'Web Development', '');
INSERT INTO XSM_xdir_cat VALUES (222, 157, 'Web Hosting', '');
INSERT INTO XSM_xdir_cat VALUES (223, 157, 'Web Services', '');
INSERT INTO XSM_xdir_cat VALUES (224, 158, 'Bands and Musicians', '');
INSERT INTO XSM_xdir_cat VALUES (225, 158, 'DJ\'s', '');
INSERT INTO XSM_xdir_cat VALUES (226, 158, 'Music Stores', '');
INSERT INTO XSM_xdir_cat VALUES (227, 158, 'Party Rentals', '');
INSERT INTO XSM_xdir_cat VALUES (228, 158, 'Video Rentals', '');
INSERT INTO XSM_xdir_cat VALUES (229, 158, 'Theatres', '');
INSERT INTO XSM_xdir_cat VALUES (230, 159, 'Accounting and Auditing', '');
INSERT INTO XSM_xdir_cat VALUES (231, 159, 'Banks', '');
INSERT INTO XSM_xdir_cat VALUES (232, 159, 'Bookkeeping', '');
INSERT INTO XSM_xdir_cat VALUES (233, 159, 'Credit Consulting', '');
INSERT INTO XSM_xdir_cat VALUES (234, 159, 'Financial Planning', '');
INSERT INTO XSM_xdir_cat VALUES (235, 159, 'Home Mortgages', '');
INSERT INTO XSM_xdir_cat VALUES (236, 159, 'Investment Services', '');
INSERT INTO XSM_xdir_cat VALUES (237, 159, 'Tax Preperation', '');
INSERT INTO XSM_xdir_cat VALUES (238, 160, 'Catering', '');
INSERT INTO XSM_xdir_cat VALUES (239, 160, 'Grocers', '');
INSERT INTO XSM_xdir_cat VALUES (240, 160, 'Health Foods', '');
INSERT INTO XSM_xdir_cat VALUES (241, 160, 'Restaurant Equipment', '');
INSERT INTO XSM_xdir_cat VALUES (242, 160, 'Specialty Foods', '');
INSERT INTO XSM_xdir_cat VALUES (243, 160, 'Wine and Liquor', '');
INSERT INTO XSM_xdir_cat VALUES (244, 161, 'Florists', '');
INSERT INTO XSM_xdir_cat VALUES (245, 161, 'Gift Baskets / Deliveries', '');
INSERT INTO XSM_xdir_cat VALUES (246, 161, 'Gifts & Specialties', '');
INSERT INTO XSM_xdir_cat VALUES (247, 161, 'Jewelers', '');
INSERT INTO XSM_xdir_cat VALUES (248, 161, 'Jewelry', '');
INSERT INTO XSM_xdir_cat VALUES (249, 162, 'Chiropractic', '');
INSERT INTO XSM_xdir_cat VALUES (250, 162, 'Dentists & Dentistry', '');
INSERT INTO XSM_xdir_cat VALUES (251, 162, 'Family Practice', '');
INSERT INTO XSM_xdir_cat VALUES (252, 162, 'Medical Clinics', '');
INSERT INTO XSM_xdir_cat VALUES (253, 162, 'Opthamology', '');
INSERT INTO XSM_xdir_cat VALUES (254, 162, 'Optometry', '');
INSERT INTO XSM_xdir_cat VALUES (255, 162, 'Plastic & Reconstructive Surgery', '');
INSERT INTO XSM_xdir_cat VALUES (256, 162, 'Pediatrics', '');
INSERT INTO XSM_xdir_cat VALUES (257, 162, 'Pharmacies', '');
INSERT INTO XSM_xdir_cat VALUES (258, 162, 'Physical Therapy', '');
INSERT INTO XSM_xdir_cat VALUES (259, 162, 'Physicians & Surgeons-MD', '');
INSERT INTO XSM_xdir_cat VALUES (260, 162, 'Products and Services', '');
INSERT INTO XSM_xdir_cat VALUES (261, 162, 'Speech Therapy', '');
INSERT INTO XSM_xdir_cat VALUES (262, 162, 'Sports Medicine', '');
INSERT INTO XSM_xdir_cat VALUES (263, 163, 'Appliance Repair', '');
INSERT INTO XSM_xdir_cat VALUES (264, 163, 'Appliances', '');
INSERT INTO XSM_xdir_cat VALUES (265, 163, 'Architecture', '');
INSERT INTO XSM_xdir_cat VALUES (266, 163, 'Building Materials', '');
INSERT INTO XSM_xdir_cat VALUES (267, 163, 'Carpet & Rug Dealers', '');
INSERT INTO XSM_xdir_cat VALUES (268, 163, 'Carpet Cleaning', '');
INSERT INTO XSM_xdir_cat VALUES (269, 163, 'Doors and Windows', '');
INSERT INTO XSM_xdir_cat VALUES (270, 163, 'Dry Cleaning', '');
INSERT INTO XSM_xdir_cat VALUES (271, 163, 'Equipment and Tools', '');
INSERT INTO XSM_xdir_cat VALUES (272, 163, 'Equipment Rental', '');
INSERT INTO XSM_xdir_cat VALUES (273, 163, 'Furniture', '');
INSERT INTO XSM_xdir_cat VALUES (274, 163, 'Furniture Repair', '');
INSERT INTO XSM_xdir_cat VALUES (275, 163, 'Gardening', '');
INSERT INTO XSM_xdir_cat VALUES (276, 163, 'H/G Retailers', '');
INSERT INTO XSM_xdir_cat VALUES (277, 163, 'House Cleaning', '');
INSERT INTO XSM_xdir_cat VALUES (278, 163, 'Interior Decorating', '');
INSERT INTO XSM_xdir_cat VALUES (279, 163, 'Laundromats', '');
INSERT INTO XSM_xdir_cat VALUES (280, 163, 'Lawn Care', '');
INSERT INTO XSM_xdir_cat VALUES (281, 163, 'Locks & Locksmiths', '');
INSERT INTO XSM_xdir_cat VALUES (282, 163, 'Lumber', '');
INSERT INTO XSM_xdir_cat VALUES (283, 163, 'Movers & Moving', '');
INSERT INTO XSM_xdir_cat VALUES (284, 163, 'Nurseries & Greenhouses', '');
INSERT INTO XSM_xdir_cat VALUES (285, 163, 'Paint and Wallcoverings', '');
INSERT INTO XSM_xdir_cat VALUES (286, 163, 'Pest Control', '');
INSERT INTO XSM_xdir_cat VALUES (287, 163, 'Playground Equipment', '');
INSERT INTO XSM_xdir_cat VALUES (288, 163, 'Pools, Spas& Saunas', '');
INSERT INTO XSM_xdir_cat VALUES (289, 163, 'Self Storage', '');
INSERT INTO XSM_xdir_cat VALUES (290, 163, 'Tile & Flooring', '');
INSERT INTO XSM_xdir_cat VALUES (291, 163, 'Tools & Hardware', '');
INSERT INTO XSM_xdir_cat VALUES (292, 163, 'Vacum Dealers', '');
INSERT INTO XSM_xdir_cat VALUES (293, 163, 'Window Cleaning', '');
INSERT INTO XSM_xdir_cat VALUES (294, 164, 'Cabinetmakers', '');
INSERT INTO XSM_xdir_cat VALUES (295, 164, 'Concrete & Brick', '');
INSERT INTO XSM_xdir_cat VALUES (296, 164, 'Electricians', '');
INSERT INTO XSM_xdir_cat VALUES (297, 164, 'Fencing & Gates', '');
INSERT INTO XSM_xdir_cat VALUES (298, 164, 'General Contractors', '');
INSERT INTO XSM_xdir_cat VALUES (299, 164, 'Home Improvement', '');
INSERT INTO XSM_xdir_cat VALUES (300, 164, 'HVAC', '');
INSERT INTO XSM_xdir_cat VALUES (301, 164, 'Landscaping', '');
INSERT INTO XSM_xdir_cat VALUES (302, 164, 'Painting', '');
INSERT INTO XSM_xdir_cat VALUES (303, 164, 'Plumbing', '');
INSERT INTO XSM_xdir_cat VALUES (304, 164, 'Pool Contractors', '');
INSERT INTO XSM_xdir_cat VALUES (305, 164, 'Roofing Contractors', '');
INSERT INTO XSM_xdir_cat VALUES (306, 164, 'Tile & Flooring Contractors', '');
INSERT INTO XSM_xdir_cat VALUES (307, 164, 'Waste Management', '');
INSERT INTO XSM_xdir_cat VALUES (308, 165, 'Auto Insurance', '');
INSERT INTO XSM_xdir_cat VALUES (309, 165, 'Health Insurance', '');
INSERT INTO XSM_xdir_cat VALUES (310, 165, 'Home Insurance', '');
INSERT INTO XSM_xdir_cat VALUES (311, 165, 'Life Insurance', '');
INSERT INTO XSM_xdir_cat VALUES (312, 165, 'Workers Comp', '');
INSERT INTO XSM_xdir_cat VALUES (313, 166, 'Attorneys', '');
INSERT INTO XSM_xdir_cat VALUES (314, 166, 'Estate and Probate Law', '');
INSERT INTO XSM_xdir_cat VALUES (315, 166, 'Law Offices', '');
INSERT INTO XSM_xdir_cat VALUES (316, 167, 'Barber Shops', '');
INSERT INTO XSM_xdir_cat VALUES (317, 167, 'Beauty Supplies', '');
INSERT INTO XSM_xdir_cat VALUES (318, 167, 'Personal Coaches', '');
INSERT INTO XSM_xdir_cat VALUES (319, 167, 'Fitness', '');
INSERT INTO XSM_xdir_cat VALUES (320, 167, 'Health Clubs', '');
INSERT INTO XSM_xdir_cat VALUES (321, 167, 'Salon & Spa', '');
INSERT INTO XSM_xdir_cat VALUES (322, 167, 'Tanning', '');
INSERT INTO XSM_xdir_cat VALUES (323, 168, 'Breeders', '');
INSERT INTO XSM_xdir_cat VALUES (324, 168, 'Grooming', '');
INSERT INTO XSM_xdir_cat VALUES (325, 168, 'Kennels & Boarding', '');
INSERT INTO XSM_xdir_cat VALUES (326, 168, 'Pet Sitting', '');
INSERT INTO XSM_xdir_cat VALUES (327, 168, 'Pet Supplies', '');
INSERT INTO XSM_xdir_cat VALUES (328, 168, 'Veterinarians', '');
INSERT INTO XSM_xdir_cat VALUES (329, 169, 'Advertising', '');
INSERT INTO XSM_xdir_cat VALUES (330, 169, 'B2B', '');
INSERT INTO XSM_xdir_cat VALUES (331, 169, 'Communications', '');
INSERT INTO XSM_xdir_cat VALUES (332, 169, 'Consulting', '');
INSERT INTO XSM_xdir_cat VALUES (333, 169, 'Courrier / Delivery Service', '');
INSERT INTO XSM_xdir_cat VALUES (334, 169, 'Employee Benefits', '');
INSERT INTO XSM_xdir_cat VALUES (335, 169, 'Employment', '');
INSERT INTO XSM_xdir_cat VALUES (336, 169, 'Graphic Design', '');
INSERT INTO XSM_xdir_cat VALUES (337, 169, 'Mail Services', '');
INSERT INTO XSM_xdir_cat VALUES (338, 169, 'Marketing Consultants', '');
INSERT INTO XSM_xdir_cat VALUES (339, 169, 'Notaries', '');
INSERT INTO XSM_xdir_cat VALUES (340, 169, 'Office Supplies', '');
INSERT INTO XSM_xdir_cat VALUES (341, 169, 'Photographers / Portraits', '');
INSERT INTO XSM_xdir_cat VALUES (342, 169, 'Printing & Print Services', '');
INSERT INTO XSM_xdir_cat VALUES (343, 169, 'Shoe Repair', '');
INSERT INTO XSM_xdir_cat VALUES (344, 169, 'Videographers', '');
INSERT INTO XSM_xdir_cat VALUES (345, 169, 'Wedding / Event Planners', '');
INSERT INTO XSM_xdir_cat VALUES (346, 170, 'Apartments', '');
INSERT INTO XSM_xdir_cat VALUES (347, 170, 'Appraisal', '');
INSERT INTO XSM_xdir_cat VALUES (348, 170, 'Escrow Services', '');
INSERT INTO XSM_xdir_cat VALUES (349, 170, 'Home Inspection', '');
INSERT INTO XSM_xdir_cat VALUES (350, 170, 'Mobile Home & Trailer Parks', '');
INSERT INTO XSM_xdir_cat VALUES (351, 170, 'Mortgage Brokers & Lenders', '');
INSERT INTO XSM_xdir_cat VALUES (352, 170, 'Property Mgmt.', '');
INSERT INTO XSM_xdir_cat VALUES (353, 170, 'Real Estate Agents', '');
INSERT INTO XSM_xdir_cat VALUES (354, 170, 'Real Estate Offices', '');
INSERT INTO XSM_xdir_cat VALUES (355, 170, 'Title Companies', '');
INSERT INTO XSM_xdir_cat VALUES (356, 171, 'American', '');
INSERT INTO XSM_xdir_cat VALUES (357, 171, 'Bagels & Donuts', '');
INSERT INTO XSM_xdir_cat VALUES (358, 171, 'Cajun', '');
INSERT INTO XSM_xdir_cat VALUES (359, 171, 'Chinese', '');
INSERT INTO XSM_xdir_cat VALUES (360, 171, 'Coffee Houses', '');
INSERT INTO XSM_xdir_cat VALUES (361, 171, 'Fast Food', '');
INSERT INTO XSM_xdir_cat VALUES (362, 171, 'Fine Dining', '');
INSERT INTO XSM_xdir_cat VALUES (363, 171, 'Ice Cream', '');
INSERT INTO XSM_xdir_cat VALUES (364, 171, 'Italian', '');
INSERT INTO XSM_xdir_cat VALUES (365, 171, 'Mexican', '');
INSERT INTO XSM_xdir_cat VALUES (366, 171, 'Other', '');
INSERT INTO XSM_xdir_cat VALUES (367, 171, 'Pizza', '');
INSERT INTO XSM_xdir_cat VALUES (368, 171, 'Sandwich & Deli', '');
INSERT INTO XSM_xdir_cat VALUES (369, 171, 'Seafood', '');
INSERT INTO XSM_xdir_cat VALUES (370, 171, 'Steak House', '');
INSERT INTO XSM_xdir_cat VALUES (371, 172, 'Accessories & Jewelry', '');
INSERT INTO XSM_xdir_cat VALUES (372, 172, 'Beauty Supplies', '');
INSERT INTO XSM_xdir_cat VALUES (373, 172, 'Books & Music', '');
INSERT INTO XSM_xdir_cat VALUES (374, 172, 'Clothing & Apparel', '');
INSERT INTO XSM_xdir_cat VALUES (375, 172, 'Department Stores', '');
INSERT INTO XSM_xdir_cat VALUES (376, 172, 'Games & Accessories', '');
INSERT INTO XSM_xdir_cat VALUES (377, 172, 'Gifts & Specialty Items', '');
INSERT INTO XSM_xdir_cat VALUES (378, 172, 'Home Electronics', '');
INSERT INTO XSM_xdir_cat VALUES (379, 172, 'Home Furnishings', '');
INSERT INTO XSM_xdir_cat VALUES (380, 172, 'Luggage & Leather goods', '');
INSERT INTO XSM_xdir_cat VALUES (381, 172, 'Photographic Equipt. & Supplies', '');
INSERT INTO XSM_xdir_cat VALUES (382, 172, 'Thrift Stores', '');
INSERT INTO XSM_xdir_cat VALUES (383, 173, 'Boats & Accessories', '');
INSERT INTO XSM_xdir_cat VALUES (384, 173, 'Cycling', '');
INSERT INTO XSM_xdir_cat VALUES (385, 173, 'Golf Courses', '');
INSERT INTO XSM_xdir_cat VALUES (386, 173, 'Golf Equipt. & Supplies', '');
INSERT INTO XSM_xdir_cat VALUES (387, 173, 'Gymnastics', '');
INSERT INTO XSM_xdir_cat VALUES (388, 173, 'Martial Arts', '');
INSERT INTO XSM_xdir_cat VALUES (389, 173, 'Paintball', '');
INSERT INTO XSM_xdir_cat VALUES (390, 173, 'Sporting Goods', '');
INSERT INTO XSM_xdir_cat VALUES (391, 173, 'Sports Facilities', '');
INSERT INTO XSM_xdir_cat VALUES (392, 174, 'Airport Shuttle', '');
INSERT INTO XSM_xdir_cat VALUES (393, 174, 'Car Rental', '');
INSERT INTO XSM_xdir_cat VALUES (394, 174, 'Hotels & Lodging', '');
INSERT INTO XSM_xdir_cat VALUES (395, 174, 'Limosine Service', '');
INSERT INTO XSM_xdir_cat VALUES (396, 174, 'Taxi Service', '');
INSERT INTO XSM_xdir_cat VALUES (397, 174, 'Travel Agencies', '');
INSERT INTO XSM_xdir_cat VALUES (398, 171, 'BBQ', '');